server:
  port: 8080
  servlet:
    context-path: /api
    multipart:  # 文件上传相关配置项
      max-file-size: 16MB # 单个文件大小
      max-request-size: 32MB # 设置总上传的文件大小


spring:
  application:
    name: SseBroadcastApplication
  # 数据库配置
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/ai_audio_transform
#    username: root
#    password: kjq
  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 16MB
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: Asia/Shanghai
# 接口文档配置
knife4j:
  enable: true
  setting:
    language: zh_cn

#mybatis-plus:
#  configuration:
#    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  global-config:
#    db-config:
#      logic-delete-field: deleted # 全局逻辑删除的实体字段名
#      logic-delete-value: 1 # 逻辑已删除值
#      logic-not-delete-value: 0 # 逻辑未删除值